spring.application.name=autenticacion-service

# Puerto del microservicio de autenticacion
server.port=8080

# URL del microservicio de usuarios (para WebClient)
usuario.service.url=http://localhost:8081

